/* Generated by BIN2S - please don't edit directly */
#pragma once
#include <stddef.h>
#include <stdint.h>

extern const uint8_t cross2d_pica_shbin[];
extern const uint8_t cross2d_pica_shbin_end[];
#if __cplusplus >= 201103L
static constexpr size_t cross2d_pica_shbin_size=396;
#else
static const size_t cross2d_pica_shbin_size=396;
#endif
